### PR TITLE
Bump and release notes for 2.12.2

### PR DESCRIPTION
**Pull request by MiguelCompany**
Bump and release notes for 2.12.2

### CODE REVIEW

**Comment by richiprosima** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/shapes_demo_docs_manual/133/)

**Review by elianalf — APPROVED** [review]

**Comment by richiprosima** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/shapes_demo_docs_manual/177/)

**Review by JesusPoderoso — CHANGES_REQUESTED** [review]
Please rebase this branch against 2.12.x so ReadTheDocs job is fixed

**Comment by richiprosima** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/shapes_demo_docs_manual/178/)

**Review by JesusPoderoso — APPROVED** [review]
LGTM

**Comment by richiprosima** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/shapes_demo_docs_manual/186/)

**Review by elianalf — APPROVED** [review]

**Pull request merged**
