### PR TITLE
2.6.1 [14579]

### PR DESCRIPTION
**Pull request by EduPonz**
Bump to 2.6.1

Signed-off-by: Eduardo Ponz <eduardoponz@eprosima.com>

### CODE REVIEW

**Review by MiguelCompany — DISMISSED** [review]
LGTM

**Comment by richiprosima** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/shapes_demo_docs_manual/41/)

**Comment by richiprosima** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/shapes_demo_docs_manual/42/)

**Review by MiguelCompany — APPROVED** [review]
LGTM

**Pull request merged**
