### PR TITLE
[20032] Bump to version v2.11.3

### PR DESCRIPTION
**Pull request by JesusPoderoso**
This PR bumps the Shapes Demo Docs version to v2.11.3 and includes the Shapes Demo v2.11.3 release notes.

Minor fix (`minor release` -> `patch release`) applied to remaining `v2.11.x` path release notes.

### CODE REVIEW

**Comment by richiprosima** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/shapes_demo_docs_manual/157/)

**Review by elianalf — CHANGES_REQUESTED** [review]

**Review by elianalf — APPROVED** [review]

**Comment by elianalf** [comment]
@richiprosima please test linux

**Comment by elianalf** [comment]
@richiprosima plase test linux

**Comment by EduPonz** [comment]
Ci actually passed [here](http://jenkins.eprosima.com:8080/job/shapes_demo_docs_manual/170/) but something went south when publishing the results to jenkins, going in!

**Pull request merged**
