### PR TITLE
[20034] Enable-Disable monitor service on shapes demo 

### PR DESCRIPTION
**Pull request by elianalf**
Add the documentation for the monitor service checkbox

Merge after:
- https://github.com/eProsima/Fast-DDS/pull/3894
- https://github.com/eProsima/Fast-DDS-docs/pull/506
- https://github.com/eProsima/ShapesDemo/pull/96

### CODE REVIEW

**Comment by richiprosima** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/shapes_demo_docs_manual/126/)

**Comment by richiprosima** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/shapes_demo_docs_manual/127/)

**Comment by richiprosima** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/shapes_demo_docs_manual/128/)

**Review by cferreiragonz — COMMENTED** [review]
LGTM with green CI. Wait for PR: https://github.com/eProsima/Fast-DDS-docs/pull/506 to update link and merge

**Pull request merged**
