### PR TITLE
[20306] Add autofill type information documentation

### PR DESCRIPTION
**Pull request by EduPonz**
This PR documents the feature added in:

* eProsima/ShapesDemo#107

### CODE REVIEW

**Comment by richiprosima** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/shapes_demo_docs_manual/155/)

**Review by JesusPoderoso — CHANGES_REQUESTED** [review]
Can you update also the following images?

- [docs/01-figures/tcp_client_options.png](https://github.com/eProsima/Shapes-Demo-Docs/blob/master/docs/01-figures/tcp_client_options.png)
- [docs/01-figures/tcp_lan_server_options.png](https://github.com/eProsima/Shapes-Demo-Docs/blob/master/docs/01-figures/tcp_lan_server_options.png)
- [docs/01-figures/tcp_wan_server_options.png](https://github.com/eProsima/Shapes-Demo-Docs/blob/master/docs/01-figures/tcp_wan_server_options.png)

**Comment by richiprosima** [comment]
Build status: [Build Status](http://jenkins.eprosima.com:8080/job/shapes_demo_docs_manual/156/)

**Review by JesusPoderoso — APPROVED** [review]
LGTM

**Comment by EduPonz** [comment]
@Mergifyio backport 2.6.x 2.10.x 2.11.x 2.12.x

**Pull request merged**
